[package]
name = "rocket-perf-test"
version = "0.1.0"
authors = ["Attila Kun <kun.attila.hun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
